### PR TITLE
Cloudflare CIDR rules and APT installation

### PR DESCRIPTION
**Pull request by oyoyo14**
CHANGELOG:
  * Add task to add private network to a tunnel:
  `cloudflared tunnel route ip add 100.64.0.0/10 8e343b13-a087-48ea-825f-9783931ff2a5`
  * Add capability to install cloudflared with Debian/Ubuntu Cloudflare repository

### CODE REVIEW

**Comment by papanito** [comment]
Thanks a lot for your PR. Looks good to me, but I would like you also update the documentation to describe the new parameters.

**Comment by papanito** [comment]
As changelog is automatically generated, can you also update your commits to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary) i.e. prefix with `feat:`, `fix:` or `docu:`.

**Comment by oyoyo14** [comment]
sure, I'll do that :)

**Comment by oyoyo14** [comment]
Done :)

**Comment by papanito** [comment]
Thanks a lot, LGTM.

**Pull request merged**
